#!/usr/bin/env python

from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper
from library.Lib import Lib

def main():
    player = Player()
    lib = Lib()
    front_end = FrontEnd(player, lib)

if __name__ == "__main__":
    main()
